language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
os:
  - linux
  - osx
script:
  - npm test
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
